"""Add timestamp to User model

Revision ID: 00a9d824589a
Revises: 50db3baccd76
Create Date: 2025-11-07 22:24:40.577181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a9d824589a'
down_revision = '50db3baccd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('return_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('return_reason')
        batch_op.drop_column('return_requested')

    # ### end Alembic commands ###
