"""Add unit and sales type to Product

Revision ID: 146255312881
Revises: 00a9d824589a
Create Date: 2025-11-15 22:05:12.479248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146255312881'
down_revision = '00a9d824589a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        # Added server_default='kg'
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=False, server_default='kg'))
        # Added server_default='retail'
        batch_op.add_column(sa.Column('sales_type', sa.String(length=20), nullable=False, server_default='retail'))
        # Added server_default='1'
        batch_op.add_column(sa.Column('min_order_quantity', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('min_order_quantity')
        batch_op.drop_column('sales_type')
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
