"""Add timestamp to Product model

Revision ID: 4e1c569de1ad
Revises: d345fdde4bbd
Create Date: 2025-10-31 21:43:39.022464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e1c569de1ad'
down_revision = 'd345fdde4bbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('agri_proof_path')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_timestamp'))
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agri_proof_path', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
