"""Add timestamp to User model

Revision ID: 50db3baccd76
Revises: 224a974effbc
Create Date: 2025-11-05 07:24:22.962261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50db3baccd76'
down_revision = '224a974effbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
